FROM python:3.10-slim

WORKDIR /app

RUN python -V && pip -V

COPY model_inference/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

COPY model_inference /app/model_inference

EXPOSE 8080

CMD ["python", "/app/model_inference/model_inference.py"]
